//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostITTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEWPOST
    {
        public Nullable<short> USERID { get; set; }
        public string SURNAME { get; set; }
        public string POSTTEXT { get; set; }
        public string POSTTYPE { get; set; }
        public string CATEGORYNAME { get; set; }
        public string TAGNAME { get; set; }
        public short POSTRANK { get; set; }
    }
}
